services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - /home/hamid/Desktop/divar/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
    - redis


  web:
    build: .
    command: /bin/sh -c "
      python manage.py wait_for_db &&
      python manage.py wait_for_redis &&
      python manage.py makemigrations  &&
      python manage.py migrate  &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "5000:80"
      - "2525:25"
    volumes:
      - ./script/tmp/mail:/smtp4dev
    restart: always
    depends_on:
      - redis
      - celery


#  celery-beat:
#    build: .
#    command: celery -A config beat --loglevel=info
#    depends_on:
#    - redis